# @package dataset
defaults:
  - nlp/default
_target_: lightning_transformers.task.nlp.language_modeling.LanguageModelingDataModule
cfg:
  dataset_name: big_patent
  dataset_config_name: d
  block_size: 512
